apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "proctor-service.name" . }}
  labels:
{{ include "proctor-service.labels" . | indent 4 }}
  annotations:
  {{- with .Values.configmap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
