apiVersion: v1
kind: Service
metadata:
  name: {{ include "proctor-service.fullname" . }}
  labels:
{{ include "proctor-service.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: proctor-service
      protocol: TCP
      name: proctor-service
  selector:
    app.kubernetes.io/name: {{ include "proctor-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
