apiVersion: v1
kind: Service
metadata:
  name: {{ include "proctor-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "proctor-service.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: proctor-service
      protocol: TCP
      name: proctor-service
  selector:
    app.kubernetes.io/name: {{ include "proctor-service.name" . }}
    app.kubernetes.io/type: service
    app.kubernetes.io/instance: {{ .Release.Name }}
