{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rbac.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "proctor-service.labels" . | indent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
