# Default values for proctor-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: walbertusd/proctor-service
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

rbac:
  create: true

nodeSelector: {}

tolerations: []

affinity: {}

migration:
  enabled : true

configmap:
  annotations: {}

config:
  ENVIRONMENT: "test"
  PROCTOR_KUBE_CONFIG: ""
  PROCTOR_KUBE_CONTEXT: "minikube"
  PROCTOR_LOG_LEVEL: "debug"
  PROCTOR_APP_PORT: "5000"
  PROCTOR_DEFAULT_NAMESPACE: "default"
  PROCTOR_REDIS_ADDRESS: "redis-master:6379"
  PROCTOR_REDIS_MAX_ACTIVE_CONNECTIONS: "10"
  PROCTOR_KUBE_JOB_ACTIVE_DEADLINE_SECONDS: "60"
  PROCTOR_KUBE_JOB_RETRIES: "0"
  PROCTOR_LOGS_STREAM_READ_BUFFER_SIZE: "140"
  PROCTOR_LOGS_STREAM_WRITE_BUFFER_SIZE: "4096"
  PROCTOR_KUBE_WAIT_FOR_RESOURCE_POLL_COUNT: "5"
  PROCTOR_KUBE_CLUSTER_HOST_NAME: "192.168.99.100:8443"
  PROCTOR_KUBE_POD_LIST_WAIT_TIME: "60"
  PROCTOR_KUBE_LOG_PROCESS_WAIT_TIME: "60"
  PROCTOR_KUBE_CA_CERT_ENCODED: ""
  PROCTOR_KUBE_BASIC_AUTH_ENCODED: ""
  PROCTOR_POSTGRES_USER: "postgres"
  PROCTOR_POSTGRES_PASSWORD: ""
  PROCTOR_POSTGRES_HOST: "postgresql"
  PROCTOR_POSTGRES_PORT: "5432"
  PROCTOR_POSTGRES_DATABASE: "proctord_test"
  PROCTOR_POSTGRES_MAX_CONNECTIONS: "50"
  PROCTOR_POSTGRES_CONNECTIONS_MAX_LIFETIME: "30"
  PROCTOR_NEW_RELIC_APP_NAME: "PROCTORD"
  PROCTOR_NEW_RELIC_LICENCE_KEY: "0123456789012345678901234567890123456789"
  PROCTOR_MIN_CLIENT_VERSION: "v2.0.0"
  PROCTOR_SCHEDULED_JOBS_FETCH_INTERVAL_IN_MINS: "5"
  PROCTOR_MAIL_USERNAME: "user@mail.com"
  PROCTOR_MAIL_PASSWORD: "password"
  PROCTOR_MAIL_SERVER_HOST: "smtp.mail.com"
  PROCTOR_MAIL_SERVER_PORT: "123"
  PROCTOR_JOB_POD_ANNOTATIONS: "{\"key.one\":\"true\"}"
  PROCTOR_SENTRY_DSN: "foo"
  PROCTOR_DOCS_PATH: "/path/to/docs/dir"
  PROCTOR_AUTH_PLUGIN_BINARY: "/app/auth.so"
  PROCTOR_AUTH_PLUGIN_EXPORTED: ""
  PROCTOR_AUTH_ENABLED: "false"
